"""Initial migration

Revision ID: 7a1e9f772ecc
Revises: 
Create Date: 2025-10-09 22:40:05.954219

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7a1e9f772ecc'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Get schema name from config (default to 'kontracts' if not set)
    schema_name = op.get_context().config.get_main_option('schema_name', 'kontracts')

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('documents',
    sa.Column('id', sa.String(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('filename', sa.Text(), nullable=False),
    sa.Column('original_name', sa.Text(), nullable=False),
    sa.Column('mime_type', sa.Text(), nullable=False),
    sa.Column('size', sa.Integer(), nullable=False),
    sa.Column('upload_path', sa.Text(), nullable=False),
    sa.Column('processing_status', sa.Text(), server_default=sa.text("'pending'::text"), nullable=False),
    sa.Column('extracted_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id', name='documents_pkey'),
    schema=schema_name
    )
    op.create_table('journal_entries',
    sa.Column('id', sa.String(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('contract_id', sa.String(), nullable=False),
    sa.Column('entry_date', sa.DateTime(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('debit_account', sa.Text(), nullable=False),
    sa.Column('credit_account', sa.Text(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('reference', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id', name='journal_entries_pkey'),
    schema=schema_name
    )
    op.create_table('journal_entry_setups',
    sa.Column('id', sa.String(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('entry_type', sa.Text(), nullable=False),
    sa.Column('trigger_event', sa.Text(), nullable=False),
    sa.Column('debit_account', sa.Text(), nullable=False),
    sa.Column('credit_account', sa.Text(), nullable=False),
    sa.Column('amount_column', sa.Text(), nullable=False),
    sa.Column('period_reference', sa.Text(), server_default=sa.text("'n'::text"), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id', name='journal_entry_setups_pkey'),
    schema=schema_name
    )
    op.create_table('leases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lease_name', sa.String(), nullable=False),
    sa.Column('lessor_name', sa.String(), nullable=False),
    sa.Column('lessee_name', sa.String(), nullable=False),
    sa.Column('contract_type', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('document_id', sa.String(), nullable=True),
    sa.Column('commencement_date', sa.Date(), nullable=False),
    sa.Column('lease_term_months', sa.Integer(), nullable=False),
    sa.Column('next_payment', sa.DateTime(), nullable=True),
    sa.Column('periodic_payment', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('payment_frequency', sa.String(), nullable=True),
    sa.Column('payment_terms', sa.String(), nullable=True),
    sa.Column('initial_direct_costs', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('prepaid_rent', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('lease_incentives', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('residual_value', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('incremental_borrowing_rate', sa.Numeric(precision=8, scale=6), nullable=True),
    sa.Column('discount_rate', sa.Numeric(precision=8, scale=6), nullable=True),
    sa.Column('classification', sa.Enum('FINANCE', 'OPERATING', name='leaseclassification', schema=schema_name), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema=schema_name
    )
    op.create_index(op.f('ix_kontracts_leases_id'), 'leases', ['id'], unique=False, schema=schema_name)
    op.create_index(op.f('ix_kontracts_leases_lease_name'), 'leases', ['lease_name'], unique=False, schema=schema_name)
    op.create_table('payments',
    sa.Column('id', sa.String(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('contract_id', sa.String(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('due_date', sa.DateTime(), nullable=False),
    sa.Column('status', sa.Text(), server_default=sa.text("'Scheduled'::text"), nullable=False),
    sa.Column('paid_date', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id', name='payments_pkey'),
    schema=schema_name
    )
    op.create_table('users',
    sa.Column('id', sa.String(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('username', sa.Text(), nullable=False),
    sa.Column('password', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('role', sa.Text(), server_default=sa.text("'Contract Administrator'::text"), nullable=False),
    sa.PrimaryKeyConstraint('id', name='users_pkey'),
    sa.UniqueConstraint('username', name='users_username_unique'),
    schema=schema_name
    )
    op.create_table('asc842_schedules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lease_id', sa.Integer(), nullable=False),
    sa.Column('initial_rou_asset', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('initial_lease_liability', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('total_payments', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('total_interest', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('total_amortization', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('schedule_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['lease_id'], ['kontracts.leases.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema=schema_name
    )
    op.create_index(op.f('ix_kontracts_asc842_schedules_id'), 'asc842_schedules', ['id'], unique=False, schema=schema_name)
    op.create_table('ifrs16_schedules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lease_id', sa.Integer(), nullable=False),
    sa.Column('initial_rou_asset', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('initial_lease_liability', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('total_payments', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('total_interest', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('total_depreciation', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('schedule_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['lease_id'], ['kontracts.leases.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema=schema_name
    )
    op.create_index(op.f('ix_kontracts_ifrs16_schedules_id'), 'ifrs16_schedules', ['id'], unique=False, schema=schema_name)
    op.create_table('lease_schedule_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lease_id', sa.Integer(), nullable=False),
    sa.Column('schedule_type', sa.String(), nullable=False),
    sa.Column('period', sa.Integer(), nullable=False),
    sa.Column('period_date', sa.Date(), nullable=False),
    sa.Column('lease_payment', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('interest_expense', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('principal_reduction', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('lease_liability_beginning', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('lease_liability_ending', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('rou_asset_beginning', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('amortization', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('rou_asset_ending', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('total_expense', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['lease_id'], ['kontracts.leases.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema=schema_name
    )
    op.create_index(op.f('ix_kontracts_lease_schedule_entries_id'), 'lease_schedule_entries', ['id'], unique=False, schema=schema_name)
    # ### end Alembic commands ###


def downgrade() -> None:
    # Get schema name from config (default to 'kontracts' if not set)
    schema_name = op.get_context().config.get_main_option('schema_name', 'kontracts')

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_kontracts_lease_schedule_entries_id'), table_name='lease_schedule_entries', schema=schema_name)
    op.drop_table('lease_schedule_entries', schema=schema_name)
    op.drop_index(op.f('ix_kontracts_ifrs16_schedules_id'), table_name='ifrs16_schedules', schema=schema_name)
    op.drop_table('ifrs16_schedules', schema=schema_name)
    op.drop_index(op.f('ix_kontracts_asc842_schedules_id'), table_name='asc842_schedules', schema=schema_name)
    op.drop_table('asc842_schedules', schema=schema_name)
    op.drop_table('users', schema=schema_name)
    op.drop_table('payments', schema=schema_name)
    op.drop_index(op.f('ix_kontracts_leases_lease_name'), table_name='leases', schema=schema_name)
    op.drop_index(op.f('ix_kontracts_leases_id'), table_name='leases', schema=schema_name)
    op.drop_table('leases', schema=schema_name)
    op.drop_table('journal_entry_setups', schema=schema_name)
    op.drop_table('journal_entries', schema=schema_name)
    op.drop_table('documents', schema=schema_name)
    # ### end Alembic commands ###
